import { CoopCategories } from '../../interfaces';

export const BasicItems = {
  [CoopCategories.Carni]: [
    'Carne',
    'Cosce di pollo',
    'Petto di pollo',
    'Salsiccia',
    'Scalopine',
    'Svizzera',
    'Wurster',
  ],
  [CoopCategories.Conserve]: ['Aceto', 'Olio cani', 'Olive', 'Sale', 'Sale grosso', 'Tonno'],
  [CoopCategories.Dolci]: ['Farina di mandorle', 'Frutta da ciucciare', 'Uova', 'Zucchero'],
  [CoopCategories.Farmacia]: ['Carta igienica', 'Dentifricio', 'Deodorante', 'Scotex'],
  [CoopCategories.FruttaVerdura]: [
    'Aglio',
    'Banana',
    'Carote',
    'Cipolle',
    'Lamponi',
    'Limoni',
    'Melanazana',
    'Mele',
    'Mirtilli',
    'Patate',
    'Pistacchio',
    'Rucula',
  ],
  [CoopCategories.LatticiniSalumi]: [
    'Brie',
    'Burro',
    'Capriccio',
    'Cotto cubetti',
    'Crudo',
    'Gorgonzola',
    'Mascarpone',
    'Mozzarella',
    'Pancetta',
    'Parmigiano',
    'Peco sardo',
    'Provolone',
    'Roquefort',
    'Salame',
    'Yogurt agnese',
    'Yogurt anna',
  ],
  [CoopCategories.PastaRiso]: ['Fusilli', 'Riso', 'Riso cani', 'Stelline', 'Tagliatelle'],
  [CoopCategories.Pesci]: [
    'Cozze',
    'Gamberetti',
    'Insalata di mare',
    'Salmone',
    'Svizzera merluzzo',
  ],
  [CoopCategories.Pulizia]: [
    'Abrillantante',
    'Carta igienica',
    'Sale lavastoviglie',
    'Sapone lavastoviglie',
    'Sapone lavatrice',
  ],
};
