export enum category {
  PESCE = 'Pesce',
  FRUTTA_VERDURA = 'Frutta e verdura',
  SALUMI = 'Salumi',
  PASTA_RIPIENA = 'Pasta ripiena',
  LATTICINI = 'Latticini',
  CARNE = 'Carne',
  DOLCI = 'Dolci',
  PASTA = 'Pasta',
  SOTTACETI = 'Sottaceti',
  PULIZIA = 'Pulizia',
  FARMACIA = 'Farmacia',
  ALTRI = 'Altri',
}

export const basicItems = {
  [category.PESCE]: ['Cozze', 'Insalata di mare', 'Salmone', 'Svizzera merluzzo'],
  [category.FRUTTA_VERDURA]: [
    'Banana',
    'Broccoli',
    'Carote',
    'Fragole',
    'Lamponi',
    'Limoni',
    'Mandarini',
    'Melanazana',
    'Mele',
    'Melone',
    'Mirtilli',
    'Peperoni',
    'Pistacchio',
    'Pomodori',
    'Rucula',
    'Zucchine',
  ],
  [category.SALUMI]: ['Cotto cubetti', 'Crudo', 'Pancetta', 'Salame'],
  [category.PASTA_RIPIENA]: ['Tortelli', 'Tortellini'],
  [category.LATTICINI]: [
    'Bastardo',
    'Burro',
    'Gorgonzola',
    'Latte',
    'Mozzarella',
    'Parmigiano',
    'Peco sardo',
    'Roquefort',
    'Tomino',
  ],
  [category.CARNE]: [
    'Carne',
    'Carne brodo',
    'Cosce di pollo',
    'Petto di pollo',
    'Salsiccia',
    'Scalopine',
    'Svizzera',
    'Wurster',
  ],
  [category.DOLCI]: ['Uova', 'Zucchero'],
  [category.PASTA]: [
    'Fusilli',
    'Gnocchi',
    'Orecchiette',
    'Riso',
    'Riso cani',
    'Stelline',
    'Tagliatelle',
  ],
  [category.SOTTACETI]: ['Aceto', 'Olio cani', 'Olive', 'Sale', 'Sale grosso', 'Tonno'],
  [category.PULIZIA]: [
    'Amorbidente',
    'Brillantante',
    'Sale lavastoviglie',
    'Sapone lavastoviglie',
    'Sapone lavatrice',
  ],
  [category.FARMACIA]: ['Carta igienica', 'Dentifricio', 'Deodorante', 'Scotex'],
  [category.ALTRI]: ['Pesto', 'Salsa orecchiette'],
};
